// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/gosukretess/battleships/internal/game"
	"github.com/gosukretess/battleships/internal/user"
)

// Injectors from wire.go:

func InitializeServers(dbPath string) (*Server, error) {
	store := user.NewStore(dbPath)
	server := user.NewServer(store)
	gameStore := game.NewStore(dbPath)
	gameServer := game.NewServer(gameStore)
	internalServer := NewServer(server, gameServer)
	return internalServer, nil
}

// wire.go:

type Server struct {
	UserServer *user.Server
	GameServer *game.Server
}

func NewServer(userServer *user.Server, gameServer *game.Server) *Server {
	return &Server{
		UserServer: userServer,
		GameServer: gameServer,
	}
}
